FLASK_APP=signanomalie
FLASK_ENV=development
FLASK_DEBUG=1
APP_TOKEN=peyK4XPibwSJ8LK0NfN1bHm5C1yUskCubfMXh77l
USER_TOKEN=VFURzUHjVHnzvZ9S4jj07NtBU0rJ1UVEYdk8KIBU
API_TOKEN=tZVVReskofnmmWQ1ErQAiePd0N3E3aduyYLxbdS1
URL=https://glpi.iut45.univ-orleans.fr/glpi-sidev/apirest.php
