FLASK_APP=signanomalie
FLASK_ENV=development
FLASK_DEBUG=1
APP_TOKEN=peyK4XPibwSJ8LK0NfN1bHm5C1yUskCubfMXh77l
USER_TOKEN=F5Q2y8b3usAcvj34Sxy5Pz1kEhWzEiiXrC5dF4jG
API_TOKEN=lLEfZ7w8jjjsVwunTg0Ctx1ZojicD4wnKBVrEAl8
URL=https://glpi.iut45.univ-orleans.fr/glpi-sidev/apirest.php